export const itemNameColors: Record<string, string> = {
  Strange: '#CF6A32',
  Unusual: '#8650AC',
  Genuine: '#4D7455',
  Vintage: '#476291',
  "Collector's": '#AA0000',
  Haunted: 'var(--color-teal-500)',
  Normal: '#B2B2B2',
  Festivized: 'var(--color-amber-600)',
  'Civilian Grade': 'var(--color-stone-500)',
  'Freelance Grade': '#5E98D9',
  'Mercenary Grade': '#4B69FF',
  'Commando Grade': '#8847FF',
  'Assassin Grade': '#D32CE6',
  'Elite Grade': '#EB4B4B',
  Killstreak: 'var(--color-pink-900)',
  'Specialized Killstreak': 'var(--color-pink-800)',
  'Professional Killstreak': 'var(--color-pink-700)',
  '(Battle Scarred)': 'var(--color-lime-950)',
  '(Well-Worn)': 'var(--color-lime-900)',
  '(Field-Tested)': 'var(--color-lime-800)',
  '(Minimal Wear)': 'var(--color-lime-700)',
  '(Factory New)': 'var(--color-lime-600)',
}
